dataset: CUB
num_class: 200
num_attribute: 312
img_size: 448
resnet_region: 196
dim_f: 2048
dim_v: 300
device: cuda:1
batch_size: 50
epochs: 200
use_unzip: True
random_seed: 5
lambda_: 0.3
lambda_reg: 0.005
normalize_V: False
tf_SAtt: True
tf_ec_layer: 1
tf_dc_layer: 1
tf_heads: 1
tf_common_dim: 300
tf_aux_embed: True
tf_dim_feedforward: 512
tf_dropout: 0.4