dataset: wurenji
num_class: 25
num_attribute: 200
img_size: 1024
resnet_region: 196
dim_f: 512
dim_v: 768
device: cuda:1
batch_size: 22
epochs: 300
use_unzip: True
random_seed: 5
lambda_: 0.3
lambda_reg: 0.005
normalize_V: False
tf_SAtt: True
tf_ec_layer: 1
tf_dc_layer: 1
tf_heads: 1
tf_common_dim: 768
tf_aux_embed: True
tf_dim_feedforward: 512
tf_dropout: 0.4